module Base where

basenum :: [String]
basenum = ["ZERO","UM","DOIS","TRES","QUATRO","CINCO","SEIS","SETE","OITO","NOVE","DEZ","ONZE","DOZE","TREZE","CATORZE","QUINZE","DEZASSEIS","DEZASSETE","DEZOITO","DEZANOVE","VINTE","VINTE E UM","VINTE E DOIS","VINTE E TRES","VINTE E QUATRO","VINTE E CINCO","VINTE E SEIS","VINTE E SETE","VINTE E OITO","VINTE E NOVE","TRINTA","TRINTA E UM","TRINTA E DOIS","TRINTA E TRES","TRINTA E QUATRO","TRINTA E CINCO","TRINTA E SEIS","TRINTA E SETE","TRINTA E OITO","TRINTA E NOVE","QUARENTA","QUARENTA E UM","QUARENTA E DOIS","QUARENTA E TRES","QUARENTA E QUATRO","QUARENTA E CINCO","QUARENTA E SEIS","QUARENTA E SETE","QUARENTA E OITO","QUARENTA E NOVE","CINQUENTA"]

basepal :: [String]
basepal = ["OFFICE","XPTO","HOME","PITBULL","PROSSEGUR","HILTON","CAO","GATO","MESA","MALA","ECRAN","BOLSA","VALORES","CHAVE","CANETA","LAPIS","PAPEL","TESOURA","ARMA","OCULOS","NOTAS","BILHETE","CARTAO","LIVRO","FOLHA","PIRAMIDE","BANCO","CADEIRA","CAIXA","DVD","LUZ","SOM","MAGNETISMO","TV","AR"]
